In [1]:
from __future__ import annotations

import pickle

from hist.intervals import clopper_pearson_interval

In [ ]:
with open("../outPickles/out_ak15.pickle", "rb") as filehandler:
    out = pickle.load(filehandler)

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2

with open("../corrections/trigEffs/AK15JetHTTriggerEfficiencyError_2017.hist", "wb") as filehandler:
    pickle.dump(error, filehandler)

In [ ]:
with open("../outPickles/out_ak8.pickle", "rb") as filehandler:
    out = pickle.load(filehandler)

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2

with open("../corrections/trigEffs/AK8JetHTTriggerEfficiencyError_2017.hist", "wb") as filehandler:
    pickle.dump(error, filehandler)

In [ ]:
with open("../outPickles/out_ak8_3d.pickle", "rb") as filehandler:
    out = pickle.load(filehandler)

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2

with open(
    "../corrections/trigEffs/AK8JetHT3DTriggerEfficiencyError_2017.hist", "wb"
) as filehandler:
    pickle.dump(error, filehandler)

In [2]:
with open("../outPickles/out_morebins.pickle", "rb") as filehandler:
    out = pickle.load(filehandler)

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2

with open(
    "../corrections/trigEffs/AK15JetHT3DTriggerEfficiencyError_2017.hist", "wb"
) as filehandler:
    pickle.dump(error, filehandler)

In [ ]:
with open("../outPickles/out_hybrid.pickle", "rb") as filehandler:
    out = pickle.load(filehandler)

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2

with open(
    "../corrections/trigEffs/HybridJetHT3DTriggerEfficiencyError_2017.hist", "wb"
) as filehandler:
    pickle.dump(error, filehandler)

In [18]:
trigEffsDict = {}
with open(
    "../../HHbbVV/corrections/trigEffs/AK15JetHT3DTriggerEfficiency_2017.hist", "rb"
) as filehandler:
    trigEffsDict["effs"] = pickle.load(filehandler)

with open(
    "../../HHbbVV/corrections/trigEffs/AK15JetHT3DTriggerEfficiencyError_2017.hist", "rb"
) as filehandler:
    trigEffsDict["effserr"] = pickle.load(filehandler)

import numpy as np
from coffea.lookup_tools.dense_lookup import dense_lookup

trigEffsLookupDict = {}
for key, effs in trigEffsDict.items():
    if "err" in key:
        trigEffsLookupDict[key] = dense_lookup(
            np.nan_to_num(effs, 0), np.squeeze(trigEffsDict[key.split("err")[0]].axes.edges)
        )
    else:
        print(effs)
        trigEffsLookupDict[key] = dense_lookup(
            np.nan_to_num(effs.view(flow=False), 0), np.squeeze(effs.axes.edges)
        )

key = "effs"
pt_1 = np.array([600, 600, 450])
msd_1 = np.array([80, 60, 80])

pt_2 = np.array([280, 320, 450])

print(out["den"])

trig_sfs = trigEffsLookupDict[key](pt_1, msd_1, pt_2)
trig_sfs_errs = trigEffsLookupDict[key + "err"](pt_1, msd_1, pt_2)

print(trig_sfs)
print(trig_sfs_errs)

trig_sfs = trigEffsLookupDict[key](pt_2, pt_1, msd_1)
trig_sfs_errs = trigEffsLookupDict[key + "err"](pt_2, pt_1, msd_1)

print(trig_sfs)
print(trig_sfs_errs)

w = trigEffsDict["effserr"]

print(w[2])

intervals = clopper_pearson_interval(out["num"].view(flow=True), out["den"].view(flow=True))
error = (intervals[1] - intervals[0]) / 2
print(error)

print(abs(intervals[1] - out["num"].view(flow=True) / out["den"].view(flow=True)))
print(abs(intervals[0] - out["num"].view(flow=True) / out["den"].view(flow=True)))

"""
import matplotlib.pyplot as plt
import mplhep as hep

for k in range(len(jet2ptbins) - 1):
    fig, ax = plt.subplots(figsize=(18, 14))
    mesh = ax.pcolormesh(jet1msdbins, jet1ptbins, w[k], cmap="viridis", vmin=0, vmax=1)
    for i in range(len(jet1ptbins) - 1):
        for j in range(len(jet1msdbins) - 1):
            if not math.isnan(w[k][i, j]): ax.text((jet1msdbins[j] + jet1msdbins[j + 1]) / 2, (jet1ptbins[i] + jet1ptbins[i + 1]) / 2, w[k][i, j].round(2), color="black", ha="center", va="center", fontsize=12)

    ax.set_title(f'{jet2ptbins[k]:.0f} < Fat Jet 2 $p_T$ < {jet2ptbins[k + 1]:.0f} (GeV)')
    ax.set_xlabel('Jet 1 MassSD (GeV)')
    ax.set_ylabel('Jet 1 $p_T$ (GeV)')
    plt.colorbar(mesh, ax=ax)
    plt.show()
    
"""

Hist(
  Regular(4, 0, 1000, name='jet2pt', label='AK15 Fat Jet 2 $p_T$ (GeV)'),
  Regular(50, 0, 1000, name='jet1pt', label='AK15 Fat Jet 1 $p_T$ (GeV)'),
  Regular(15, 0, 300, name='jet1msd', label='AK15 Fat Jet 1 MassSD (GeV)'),
  storage=Double()) # Sum: nan (nan with flow)
Hist(
  Variable([0, 250, 300, 350, 400, 500, 750, 1000]),
  Regular(50, 0, 1000, name='jet1pt', label='AK15 Fat Jet 1 $p_T$ (GeV)'),
  Regular(15, 0, 300, name='jet1msd', label='AK15 Fat Jet 1 MassSD (GeV)'),
  storage=Double()) # Sum: 20165584.0 (33568398.0 with flow)
[0. 0. 0.]
[0.5 0.5 0.5]
[0.9985119  0.99858357 0.71386768]
[0.0361673  0.01335532 0.01465058]
[[5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01]
 [5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01
  5.00000000e-01 5.00000000e

/Users/cmantill/miniconda3/envs/hww/lib/python3.7/site-packages/ipykernel_launcher.py:47: RuntimeWarning: invalid value encountered in true_divide
/Users/cmantill/miniconda3/envs/hww/lib/python3.7/site-packages/ipykernel_launcher.py:48: RuntimeWarning: invalid value encountered in true_divide


'\nimport matplotlib.pyplot as plt\nimport mplhep as hep\n\nfor k in range(len(jet2ptbins) - 1):\n    fig, ax = plt.subplots(figsize=(18, 14))\n    mesh = ax.pcolormesh(jet1msdbins, jet1ptbins, w[k], cmap="viridis", vmin=0, vmax=1)\n    for i in range(len(jet1ptbins) - 1):\n        for j in range(len(jet1msdbins) - 1):\n            if not math.isnan(w[k][i, j]): ax.text((jet1msdbins[j] + jet1msdbins[j + 1]) / 2, (jet1ptbins[i] + jet1ptbins[i + 1]) / 2, w[k][i, j].round(2), color="black", ha="center", va="center", fontsize=12)\n\n    ax.set_title(f\'{jet2ptbins[k]:.0f} < Fat Jet 2 $p_T$ < {jet2ptbins[k + 1]:.0f} (GeV)\')\n    ax.set_xlabel(\'Jet 1 MassSD (GeV)\')\n    ax.set_ylabel(\'Jet 1 $p_T$ (GeV)\')\n    plt.colorbar(mesh, ax=ax)\n    plt.show()\n    \n'