In [57]:
import uproot
import awkward as ak
from coffea import nanoevents
from coffea.nanoevents.methods.base import NanoEventsArray
from coffea.analysis_tools import PackedSelection

from coffea.nanoevents.methods import vector
from coffea.lookup_tools.dense_lookup import dense_lookup

ak.behavior.update(vector.behavior)

import pickle
import numpy as np

from typing import Optional, List, Dict
from copy import copy

import matplotlib.pyplot as plt
import mplhep as hep
from matplotlib import colors

from tqdm import tqdm
import fastjet
import jetnet

import os


In [2]:
plot_dir = "../../../plots/ScaleFactors/Nov16"
_ = os.system(f"mkdir -p {plot_dir}")


In [3]:
events = nanoevents.NanoEventsFactory.from_root(
    # "/eos/uscms/store/user/lpcpfnano/cmantill/v2_3/2017/HH_gen/GluGluToHHTobbVV_node_cHHH1_TuneCP5_13TeV-powheg-pythia8/GluGluToHHTobbVV_node_cHHH1/221017_221918/0000/nano_mc2017_100.root",
    "/eos/uscms/store/user/lpcpfnano/drankin/v2_2/2017/TTbar/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/TTToSemiLeptonic_ext1/211112_132937/0000/nano_mc2017_100.root",
    schemaclass=nanoevents.NanoAODSchema,
).events()


/uscms_data/d3/rkansal/mambaforge/envs/python39/lib/python3.9/site-packages/coffea/nanoevents/mapping/uproot.py:75: UserWarning: Found duplicate branch FatJetAK15SubJet_nBHadrons in <TTree 'Events' (1950 branches) at 0x7f2c8441b850>, taking first instance
  warnings.warn(
/uscms_data/d3/rkansal/mambaforge/envs/python39/lib/python3.9/site-packages/coffea/nanoevents/mapping/uproot.py:75: UserWarning: Found duplicate branch FatJetAK15SubJet_nCHadrons in <TTree 'Events' (1950 branches) at 0x7f2c8441b850>, taking first instance
  warnings.warn(
/uscms_data/d3/rkansal/mambaforge/envs/python39/lib/python3.9/site-packages/coffea/nanoevents/mapping/uproot.py:75: UserWarning: Found duplicate branch FatJetAK15_nBHadrons in <TTree 'Events' (1950 branches) at 0x7f2c8441b850>, taking first instance
  warnings.warn(
/uscms_data/d3/rkansal/mambaforge/envs/python39/lib/python3.9/site-packages/coffea/nanoevents/mapping/uproot.py:75: UserWarning: Found duplicate branch FatJetAK15_nCHadrons in <TTree 'Eve

### Boosted Top Pre-selection

Based on selection in https://indico.cern.ch/event/1208247/#10-lund-plane-reweighting-for

In [4]:
def pad_val(
    arr: ak.Array,
    target: int,
    value: float,
    axis: int = 0,
    to_numpy: bool = True,
    clip: bool = True,
):
    """
    pads awkward array up to ``target`` index along axis ``axis`` with value ``value``,
    optionally converts to numpy array
    """
    ret = ak.fill_none(ak.pad_none(arr, target, axis=axis, clip=clip), value, axis=axis)
    return ret.to_numpy() if to_numpy else ret


def add_selection(
    name: str,
    sel: np.ndarray,
    selection: PackedSelection,
    cutflow: dict = None,
    isData: bool = False,
    signGenWeights: ak.Array = None,
):
    """adds selection to PackedSelection object and the cutflow dictionary"""
    selection.add(name, sel)
    if cutflow is not None:
        cutflow[name] = (
            np.sum(selection.all(*selection.names))
            if isData
            # add up sign of genWeights for MC
            else np.sum(signGenWeights[selection.all(*selection.names)])
        )


preselection_cut_vals = {"pt": 250, "msd": 20}
num_jets = 1

preselection_cut = np.prod(
    pad_val(
        (events.FatJet.pt > preselection_cut_vals["pt"])
        * (events.FatJet.msoftdrop > preselection_cut_vals["msd"]),
        num_jets,
        False,
        axis=1,
    ),
    axis=1,
).astype(bool)

presel_events = events[preselection_cut]


In [5]:
isData = False
signGenWeights = None if isData else np.sign(presel_events["genWeight"])
n_events = len(presel_events) if isData else int(np.sum(signGenWeights))
selection = PackedSelection()

cutflow = {}
cutflow["presel"] = len(presel_events)


In [6]:
d_PDGID = 1
b_PDGID = 5
g_PDGID = 21
TOP_PDGID = 6

ELE_PDGID = 11
vELE_PDGID = 12
MU_PDGID = 13
vMU_PDGID = 14
TAU_PDGID = 15
vTAU_PDGID = 16

Z_PDGID = 23
W_PDGID = 24
HIGGS_PDGID = 25

b_PDGIDS = [511, 521, 523]

GRAV_PDGID = 39

GEN_FLAGS = ["fromHardProcess", "isLastCopy"]

FILL_NONE_VALUE = -99999


skim_vars = {
    "eta": "eta",
    "phi": "phi",
    "mass": "mass",
    "pt": "pt",
}

# finding the two gen tops
tops = presel_events.GenPart[
    (abs(presel_events.GenPart.pdgId) == TOP_PDGID) * presel_events.GenPart.hasFlags(GEN_FLAGS)
]


In [7]:
deltaR = 0.8


In [8]:
tops_children = tops.distinctChildren
tops_children = tops_children[tops_children.hasFlags(GEN_FLAGS)]
ws = ak.flatten(tops_children[np.abs(tops_children.pdgId) == W_PDGID], axis=2)
had_top_sel = np.all(np.abs(ws.children.pdgId) <= 5, axis=2)
had_ws = ak.flatten(ws[had_top_sel])
had_tops = ak.flatten(tops[had_top_sel])
had_top_children = ak.flatten(tops_children[had_top_sel], axis=1)
had_bs = had_top_children[np.abs(had_top_children.pdgId) == 5]
add_selection(
    "hadronic bs", np.any(had_bs.pdgId, axis=1), selection, cutflow, isData, signGenWeights
)


In [9]:
had_w_jet_match = ak.all(had_ws.children.delta_r(presel_events.FatJet[:, 0]) < deltaR, axis=1)
had_b_jet_match = ak.flatten(
    pad_val(had_bs.delta_r(presel_events.FatJet[:, 0]) < deltaR, 1, False, axis=1, to_numpy=False)
)
merged_top_jet_match = had_w_jet_match * had_b_jet_match


In [ ]:
# had_top_jet_match = presel_events.FatJet[:, 0].delta_r(hadronic_tops) < deltaR
# add_selection("jet not matched", ~had_top_jet_match, unmatched_selection)


In [10]:
merged_top_events = presel_events[merged_top_jet_match]
had_top_jets = merged_top_events.FatJet[:, 0]

merged_ak8_pfcands = merged_top_events.FatJetPFCands
merged_ak8_pfcands = merged_ak8_pfcands[merged_ak8_pfcands.jetIdx == 0]
merged_pfcands = merged_top_events.PFCands[merged_ak8_pfcands.pFCandsIdx]


In [11]:
merged_pfcands_vector_ptetaphi = ak.Array(
    [
        [{kin_key: cand[kin_key] for kin_key in skim_vars} for cand in event_cands]
        for event_cands in merged_pfcands
    ],
    with_name="PtEtaPhiMLorentzVector",
)


In [12]:
# jet definitions
dR = 0.8
cadef = fastjet.JetDefinition(fastjet.cambridge_algorithm, dR)
ktdef = fastjet.JetDefinition(fastjet.kt_algorithm, dR)


In [35]:
# cluster first with kT
kt_clustering = fastjet.ClusterSequence(merged_pfcands_vector_ptetaphi, ktdef)
kt_subjets = kt_clustering.exclusive_jets(3)
kt_subjets_pt = np.sqrt(kt_subjets.px ** 2 + kt_subjets.py ** 2)
kt_subjet_consts = kt_clustering.exclusive_jets_constituents(3)

# then re-cluster with CA
# won't need to flatten once https://github.com/scikit-hep/fastjet/pull/145 is released
ca_clustering = fastjet.ClusterSequence(ak.flatten(kt_subjet_consts, axis=1), cadef)
lds = ak.flatten(ca_clustering.exclusive_jets_lund_declusterings(1), axis=1)


In [120]:
def get_ld_indices(vals, edges):
    indices = []

    for val, edge in zip(vals, edges):
        indices.append(
            np.clip(
                np.searchsorted(edge, val, side="right")
                - 1,
                0,
                len(edge) - 2,
            )
        )

    return indices

In [129]:
f = uproot.open("/uscms_data/d3/oamram/Misc/LundReweighting/ratio_ktjets_nov7.root")

# 3D histogram: [subjet_pt, ln(0.8/Delta), ln(kT/GeV)]
ratio_nom = f['ratio_nom'].to_numpy()
ratio_nom_edges = ratio_nom[1:]
ratio_nom = ratio_nom[0]
ratio_nom_lookup = dense_lookup(ratio_nom, ratio_nom_edges)
ratio_nom_errs_lookup = dense_lookup(f['ratio_nom'].errors(), ratio_nom_edges)

In [118]:
# save offsets to 
ld_offsets = lds.kt.layout.offsets
flat_logD = np.log(0.8/ak.flatten(lds).Delta).to_numpy()
flat_logkt = np.log(ak.flatten(lds).kt).to_numpy()
# repeat subjet pt for each lund declustering
flat_subjet_pt = np.repeat(ak.flatten(kt_subjets_pt), ak.count(lds.kt, axis=1)).to_numpy()

In [121]:
# get lund plane bins
inds = get_ld_indices((flat_subjet_pt, flat_logD, flat_logkt), ratio_nom_edges)
# convert 3D indices to single scalar
scalar_inds = np.ravel_multi_index(inds, ratio_nom.shape)

In [130]:
ratio_nom[tuple(inds)]

array([0.92324436, 0.90136653, 0.97770345, ..., 0.9449471 , 1.0411583 ,
       1.0922482 ], dtype=float32)

In [132]:
ratio_nom.reshape(-1)[]

array([0.92324436, 0.90136653, 0.97770345, ..., 0.9449471 , 1.0411583 ,
       1.0922482 ], dtype=float32)

In [111]:
ratio_nom[0].shape

(6, 20, 20)

In [110]:
len(ratio_nom[1])

7

In [88]:
ld_offsets = lds.kt.layout.offsets

In [82]:
ak.flatten(lds).kt.to_numpy()

array([1.48361689, 0.60492159, 0.25005975, ..., 0.270007  , 0.34943345,
       0.02051957])

In [93]:
re_ld = ak.Array(ak.layout.ListOffsetArray64(ld_offsets, ak.layout.NumpyArray(ak.flatten(lds).kt.to_numpy())))

In [75]:
lds = ak.flatten(lds, axis=1)

In [73]:
np.searchsorted([0, 1, 2], ldsf.kt, side="right")

TypeError: to_rectilinear argument must be iterable

ValueError: in ListOffsetArray64, cannot convert to RegularArray because subarray lengths are not regular

(https://github.com/scikit-hep/awkward-1.0/blob/1.10.2/src/cpu-kernels/awkward_ListOffsetArray_toRegularArray.cpp#L22)

In [69]:
ldsf = ak.flatten(lds, axis=1)

In [62]:
lds

<Array [[[{Delta: 0.255, ... kt: 0.0205}]]] type='3192 * var * var * {"Delta": f...'>